Adjunto Ejercicio Entregable de Videojuego con Herencia y Polimorfismo
lau-ruspil/entregables-olavarria pull request #3
Opened 2024-10-13 22:18 UTC by lau-ruspil

2024-10-15 00:42 UTC, SofiZ2001 requested changes
Algunos comments Lau! Cualquier cosa avisame

2024-10-15 00:42 UTC, SofiZ2001 commented on ejercicioVideojuego/Luchador.ts
> +	subirNivel(): void {
Agregar modificadores de acceso a las funciones
(Replicar en las demas clases hijas)

2024-10-15 00:42 UTC, SofiZ2001 commented on ejercicioVideojuego/Mago.ts
> +	protected puntosDeVida: number;
Estos atributos ya los tiene el padre, no es necesario que los tenga el hijo tambien

2024-10-15 00:42 UTC, SofiZ2001 commented on ejercicioVideojuego/Luchador.ts
> +	protected puntosDeVida: number;
Estos atributos ya los tiene el padre, no es necesario que los tenga el hijo tambien

2024-10-15 00:42 UTC, SofiZ2001 commented on ejercicioVideojuego/Arquero.ts
> +	protected puntosDeVida: number;
Estos atributos ya los tiene el padre, no es necesario que los tenga el hijo tambien
(Replicar en las demas clases hijas)

2024-10-15 00:42 UTC, SofiZ2001 commented on ejercicioVideojuego/Mago.ts
> +	}
La funcionalidad de atacar debería restarle la vida a **otro** personaje.
Para eso, atacar debería recibir por parámetro el personaje al que quiere atacar
Si ese personaje aun le queda vida, se le restan x puntos a ese personaje
Si no, el personaje que ataco es el vencedor.

Por otro lado, si la funcion atacar es la misma para todas las clases hijas, no tiene sentido que las implementen ellas. Sino el padre Personaje (siempre abstraer toda informacion en comun hacia el padre)

2024-10-15 00:42 UTC, SofiZ2001 commented on ejercicioVideojuego/Mago.ts
> +	}
Idem con la funcionalidad de atacar, esto es igual en todas las clases hijas. Tenes dos opciones:
1) abstraes la informacion a la clase Padre
2) Pensas de alguna forma en la que cada clase hija implemente esta funcion de una forma diferente a las demás

2024-10-15 00:42 UTC, SofiZ2001 commented on ejercicioVideojuego/Mago.ts
> +	}
Idem con la funcionalidad de atacar, esto es igual en todas las clases hijas. Tenes dos opciones:
1) abstraes la informacion a la clase Padre
2) Pensas de alguna forma en la que cada clase hija implemente esta funcion de una forma diferente a las demás

2024-10-15 03:09 UTC, lau-ruspil commented on ejercicioVideojuego/Luchador.ts
> +	subirNivel(): void {
Tenes razón Sofi, siempre me olvido de eso. las doy por hecho que son públicas. Pero es buena práctica.

2024-10-15 03:13 UTC, lau-ruspil commented on ejercicioVideojuego/Mago.ts
> +	}
Si tal cual, lo correcto sería que si ataca que le reste vida al otro personaje. Sinceramente no me enrosque mucho y lo simplifique bastante. Eso me trajo como consecuencia todos estos comments ajajaj. Voy a modificar todo ahora y lo vuelvo a subir. Gracias Sofi!!!

2024-10-15 16:17 UTC, lau-ruspil commented
Hola Sofi, en el main.ts importe la clase padre Pesonaje de gusto. Es la costumbre de importar cuando trabajo en otros archivos. No le des importancia a esa primer linea.

2024-10-18 12:28 UTC, SofiZ2001 approved these changes
LG2M

2024-10-18 18:27 UTC, merged